### PR TITLE
7 replace cartoon avatars with actual images

### LINKED ISSUE #7: Dashboards Home page
reference : https://docs.google.com/presentation/d/1UJIhM-JRrLuSAvsiC-wZEpvy6SA8tPCG/edit#slide=id.p5

- [ ] Use actual photos to replace the cartoons.([new photos](https://drive.google.com/drive/u/1/folders/128ahNu0YFbkR8ylf1YqqH47xCgqqsrn-))

### PR DESCRIPTION
**Pull request by machariamuguku**
Fixes #7

### CODE REVIEW

**Comment by machariamuguku** [comment]
@rowo This might need a design review

**Comment by rowo** [comment]
@machariamuguku is there an easy way to view this in the site and a folder of the images I can access?

**Comment by machariamuguku** [comment]
@rowo You've been given access to the images folder. I'm sharing the env file with you so you can clone and run this locally.

**Comment by peterMuriuki** [comment]
> @rowo You've been given access to the images folder. I'm sharing the env file with you so you can clone and run this locally.

@machariamuguku please add a a screen recording or a snapshots of the page, so that they can be reviewed much quicker.

**Comment by machariamuguku** [comment]
> > @rowo You've been given access to the images folder. I'm sharing the env file with you so you can clone and run this locally.
> 
> @machariamuguku please add a a screen recording or a snapshots of the page, so that they can be reviewed much quicker.

Before changes

Screenshot 2021-04-13 at 09 32 08

After Changes
Screenshot 2021-04-13 at 13 22 33

**Review by moshthepitt — CHANGES_REQUESTED** [review]
I could be wrong, but it looks like the new image for "Nutrition" seems to have its aspect ratio messed up.  Could you fix that please, and investigate that it does not happen for the other two?

**Comment by machariamuguku** [comment]
> I could be wrong, but it looks like the new image for "Nutrition" seems to have its aspect ratio messed up. Could you fix that please, and investigate that it does not happen for the other two?

fixed

**Comment by machariamuguku** [comment]
> I could be wrong, but it looks like the new image for "Nutrition" seems to have its aspect ratio messed up. Could you fix that please, and investigate that it does not happen for the other two?

fixed

**Comment by moshthepitt** [comment]
LGTM but let's let @rowo take a look

**Comment by rowo** [comment]
I will edit the image coloring

@machariamuguku On the MIECD site, are the images always in the ratio in the screenshot, https://github.com/OpenSRP/miecd/pull/20#issuecomment-818479684, or do they follow the width of the grey container behind it? I guess I’m wondering at narrow and wide browser widths, do they images look okay at their current ratio? I guess it doesn't matter if the images are all the same size and behave the same.

**Comment by machariamuguku** [comment]
> I will edit the image coloring
> 
> @machariamuguku On the MIECD site, are the images always in the ratio in the screenshot, [#20 (comment)](https://github.com/OpenSRP/miecd/pull/20#issuecomment-818479684), or do they follow the width of the grey container behind it? I guess I’m wondering at narrow and wide browser widths, do they images look okay at their current ratio? I guess it doesn't matter if the images are all the same size and behave the same.

They scale linearly, following the width of the container at a ratio. They always fit the container without stretching

**Comment by rowo** [comment]
@machariamuguku here are some images where I matched the nutrition image to same ratio as the other two and tried to normalize the color. In my opinion, it would look better to put the images within the container now that they are full-bleed photos and not cutout illustrations, but I understand if that's not possible for the project.

Nutrition  (1)-sm
Pregnancy  (2)-sm
PNC   NBC (2)-sm
Nutrition  (1)-md
Pregnancy  (2)-md
PNC   NBC (2)-md
Nutrition  (1)-lg
Pregnancy  (2)-lg
PNC   NBC (2)-lg

**Comment by machariamuguku** [comment]
> In my opinion, it would look better to put the images within the container now that they are full-bleed photos and not cutout illustrations

@rowo I could try that.

Are you thinking more of this 
card_1

or this?
card_2

**Comment by machariamuguku** [comment]
@rowo In hindsight, due to timelines, I think we can schedule these changes for the future

**Review by peterMuriuki — APPROVED** [review]

**Comment by moshthepitt** [comment]
> I think we can schedule these changes for the future

@machariamuguku could you add an issue for this?

**Review by moshthepitt — APPROVED** [review]

**Pull request merged**
