### PR TITLE
Patient details view

### PR DESCRIPTION
**Pull request by peterMuriuki**
work towards closing #15 
- Refactor the basic information component(include more rows of key:value pairs)
- Style tweaks to enlarge the message row in the reports table
- Refactor ReportsTable:
	- to functional component
	- move util functions outside component
	- Add utils and charts for adding mothe'rs blood pressure, child wieght and height
- Refactor Chart component to accept more than one data series
- selector to select smsEvents based on client_id

### CODE REVIEW

**Comment by moshthepitt** [comment]
@p-netm could we have a screenshot?

**Comment by peterMuriuki** [comment]
@moshthepitt 
patientDetails

**Comment by moshthepitt** [comment]
is it expected to have so many nulls in the patient view as in your screenshot?

**Comment by peterMuriuki** [comment]
> is it expected to have so many nulls in the patient view as in your screenshot?

will create an issue to address this. https://github.com/opensrp/miecd/issues/40

**Review by KipSigei — APPROVED** [review]

**Review by moshthepitt — APPROVED** [review]

**Pull request merged**
