### PR TITLE
14 compartments overview

### LINKED ISSUE #14: Compartments overview(with circles) for all modules
references: 
https://docs.google.com/presentation/d/1UJIhM-JRrLuSAvsiC-wZEpvy6SA8tPCG/edit#slide=id.p10
https://docs.google.com/presentation/d/1UJIhM-JRrLuSAvsiC-wZEpvy6SA8tPCG/edit#slide=id.p11

- [x] make headings bigger in size
- [x] add spacing between lines (line spacing between numbers and text inside the circles)
- [x] There is no spacing between lines here? (between the numbers and the texts).
- [x] change inappropriate feeding circle colour so it's not similar to wasting group
- [x] No total number displayed for nutrition module

### PR DESCRIPTION
**Pull request by machariamuguku**
Fixes #14 

- Commits 8d9a9458815a82600b68d47803f82470168bc062 and b155a5ecdb7b99096ca91befb62ca16107bdbefc fixes the dateRange calculation such that:

1. If age range starts at 0 and ends at x, both age 0 and age x are within range. For example both 0 and 2 are valid for age range 0-2
2. If age range starts at y, such that y > 0, and ends at z, y is exclusive (not within range) but z is within range. For example for age range 2-5, 2 is not within range but 5 is. i.e, anything above 2 is within range but 2 itself is not

### CODE REVIEW

**Comment by machariamuguku** [comment]
@ageryck confirm that the age's to be displayed on compartments for nutrition are for age ranges 0-2 and 2-5 and not for ages 0-2 and 0-5

**Review by ashfahan — DISMISSED** [review]

**Comment by ageryck** [comment]
> @ageryck confirm that the age's to be displayed on compartments for nutrition are for age ranges 0-2 and 2-5 and not for ages 0-2 and 0-5

@machariamuguku document states under 2 and under 5 - this means this 0-2 and 0-5, under 2 is a subset of under 5. Following for further clarification still.

**Comment by machariamuguku** [comment]
> @machariamuguku document states under 2 and under 5 - this means this 0-2 and 0-5, under 2 is a subset of under 5. Following for further clarification still.

@ageryck also follow up on age calculations and whether months matter. I.e whether `2 years and 2 months` should be in range 0-2 or 2-5

**Comment by machariamuguku** [comment]
~~@ageryck According to the technical documentation, the child range covered for the nutrition module is 0-5 years, this means that the totals rows added as per #14 is similar to the 0-5 range. It doesn't make sense to have two similar metrics. I propose we keep ranges 0-2, 2-5 and total (0-5), which is the current state of this PR. About age calculations, this PR interprets age 2 years and 2 months as in range 2-5 and not 0-2. I propose this be merged as is~~

**Comment by machariamuguku** [comment]
@ageryck disregard previous comment, I've revisited the change request and the technical documentation and discovered the change requested is totals on compartment headers and not a new totals row. I've also reverted the filters to 0-2 and 0-5.

**Review by peterMuriuki — DISMISSED** [review]

**Review by ashfahan — APPROVED** [review]

**Review by peterMuriuki — APPROVED** [review]

**Pull request merged**
